version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: html-proofer
    versions:
    - 3.18.5
    - 3.18.6
    - 3.18.8
    - 3.19.0
  - dependency-name: github-pages
    versions:
    - "211"
    - "212"
    - "213"
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: jekyll-octicons
    versions:
    - 11.3.0
    - 12.0.0
    - 12.1.0
